In [19]:
import numpy as np
from scipy.optimize import linprog

In [20]:
INF_CONST = 100_000

In [74]:
list(range(3, 0, -1))

[3, 2, 1]

In [36]:
# finding the nash equilibrium for rock paper scisors using mixed strategies
A = np.array([
    [0, -1, 1],
    [1, 0, -1],
    [-1, 1, 0],
])
A

array([[ 0, -1,  1],
       [ 1,  0, -1],
       [-1,  1,  0]])

In [42]:
Nx = 3
Nu = 3
c = np.array([0.0, 0.0, 0.0, 1.0])
# c = c[np.newaxis, :] # not sure about shape
A_ub = np.c_[A, -np.ones( A.shape[0] )]
b_ub = np.zeros(A.shape[1])

A_eq = np.array([[1.0, 1.0, 1.0, 0.0]])
A_eq.shape
b_eq = np.array([1.0])

l_b = np.array([0.0, 0.0, 0.0, -np.inf])
u_b = np.array([1.0, 1.0, 1.0, np.inf])

# bounds = [(0, 1), (0, 1), (0, 1), (-np.inf, np.inf)]
bounds = np.column_stack( ( l_b, u_b ))

In [66]:
np.ones((1, Nu))

array([[1., 1., 1.]])

In [55]:
res = linprog(c=c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=bounds)
y = res.x[: -1]

In [41]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

# Create a sequence by stacking the arrays vertically
sequence = np.column_stack((array1, array2))
sequence.tolist()

[[1, 6], [2, 7], [3, 8], [4, 9], [5, 10]]

In [73]:
z = np.array([1,2,3,4])
np.concatenate( ( z, z ) )

array([1, 2, 3, 4, 1, 2, 3, 4])

In [57]:
A

array([[ 0, -1,  1],
       [ 1,  0, -1],
       [-1,  1,  0]])

In [58]:
y

array([0.33333333, 0.33333333, 0.33333333])